### ISSUE TITLE
ValueError: Cannot feed value of shape (0, 0) for Tensor 'Placeholder_1:0', which has shape '(?, 10)'

### ISSUE THREAD

**Issue by jaminearly96** [aqibsaeed/Urban-Sound-Classification#18]
Traceback (most recent call last):
  File "/neuralNet.py", line 160, in <module>
    _, cost = sess.run([optimizer, cost_function], feed_dict={X: train_x, Y: train_y})
  File "\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))

Running near exact code, with the only addition being 'import librosa.display'

**Comment by jaminearly96** [comment]
Was an issue with file path!!

**Comment by souzapaulino** [comment]
Erhmeh, 
how did you solve it?
