### ISSUE TITLE
NoBackendError

### ISSUE THREAD

**Issue by xiaoyongzhu** [aqibsaeed/Urban-Sound-Classification#9]
Just want to raise this issue in case someone also encountered this (and share my solution). I will get this no backend error:
```
Traceback (most recent call last):
  File "CNNClassifier.py", line 54, in <module>
    features,labels = extract_features(parent_dir,sub_dirs)
  File "CNNClassifier.py", line 25, in extract_features
    sound_clip,s = librosa.load(fn)
  File "/datadrive/xiaoyzhu/python2env/local/lib/python2.7/site-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/datadrive/xiaoyzhu/python2env/local/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()

```

In Ubuntu, I use 
`sudo apt-get install libav-tools`

and this issue get solved.

**Comment by aqibsaeed** [comment]
Thank you. For the time being, I am leaving this issue opened.

**Comment by ahsan4415** [comment]
How solve this issue in window using anaconda??

**Comment by ahsan4415** [comment]
the error  invalid literal for int() with base 10 in following line how can i fix it??
 return np.array(features), np.array(labels,dtype = np.int)

**Comment by munirKarsli** [comment]
> the error invalid literal for int() with base 10 in following line how can i fix it??
> return np.array(features), np.array(labels,dtype = np.int)

i have same problem. Did anyone fix it?

**Comment by samisherif95** [comment]
is there anyway to fix this problem if you are working on a Mac using pycharm ??/ need help asap please.

**Comment by munirKarsli** [comment]
i didn't find anyway to fix this problem. I write new code for audio-classification. if you want you can look my github repo

**Comment by playma** [comment]
Just remove all `.DS_store` file in the data directory

**Comment by souzapaulino** [comment]
When I run, this error came up:

ValueError: Cannot feed value of shape (0, 0) for Tensor 'Placeholder_1:0', which has shape '(?, 10)'
